#!/bin/sh
# check if we are on real system
if [ -z "${IPKG_INSTROOT}" ]; then
	ZAPRET_DIR=/opt/zapret2
	ZAPRET_INITD=/etc/init.d/zapret2
	ZAPRET_CFG=/etc/config/zapret2
	if [ -f "${ZAPRET_INITD}" ]; then
		SCRIPT=$( readlink "${ZAPRET_INITD}" )
		if [ -n "${SCRIPT}" ]; then
			echo "Please uninstall incompatible \"zapret2\" service!"
			exit 44
		fi
	fi
	if command -v apk >/dev/null; then
		PKG_MGR="apk"
		PKG_CHECK="apk info -e "
		PKG_REMOVE="apk del --force "
	else
		PKG_MGR="opkg"
		PKG_CHECK="opkg status "
		PKG_REMOVE="opkg remove --force-remove "
	fi
	if [ "${PKG_UPGRADE}" = "1" ]; then
		# stop service if PKG_UPGRADE
		if [ -x "${ZAPRET_INITD}" ]; then
			${ZAPRET_INITD} running && ${ZAPRET_INITD} stop >/dev/null 2>&1
		fi
	fi
	if ${PKG_CHECK} zapret2 2>/dev/null | grep -q . ; then
		if [ ! -f "/opt/zapret2/sync_config.sh" ]; then
			echo "Please uninstall incompatible \"zapret2\" package!"
			exit 47
		fi
		if [ -f "${ZAPRET_CFG}" ] && ! grep -q "run_on_boot" "${ZAPRET_CFG}"; then
			echo "Please uninstall incompatible \"zapret2\" package!"
			exit 48
		fi
	fi
	if ${PKG_CHECK} luci-app-zapret2 2>/dev/null | grep -q . ; then
		SVC_FILE=/www/luci-static/resources/view/zapret2/service.js
		if [ ! -f "${SVC_FILE}" ] || ! grep -Fq "/remittor/zapret-openwrt" "${SVC_FILE}"; then
			echo "Please uninstall incompatible \"luci-app-zapret2\" package!"
			exit 55
		fi
	fi
	if [ -f "${ZAPRET_CFG}" ] && ! grep -q "run_on_boot" "${ZAPRET_CFG}"; then
		if [ -x "${ZAPRET_INITD}" ]; then
			${ZAPRET_INITD} running && ${ZAPRET_INITD} stop >/dev/null 2>&1
		fi
		rm -f ${ZAPRET_CFG}
		rm -f ${ZAPRET_INITD}
		[ -d "${ZAPRET_DIR}" ] && rm -rf ${ZAPRET_DIR}
		echo "All files of the previously installed package have been removed!"
	fi
	if ${PKG_CHECK} zapret2-mdig 2>/dev/null | grep -q . ; then
		${PKG_REMOVE} zapret2-mdig
	fi
	if ${PKG_CHECK} zapret2-ip2net 2>/dev/null | grep -q . ; then
		${PKG_REMOVE} zapret2-ip2net
	fi
	if [ ! -d "${ZAPRET_DIR}" ]; then
		mkdir -p ${ZAPRET_DIR}
	fi
fi
exit 0
