#!/bin/sh
# check if we are on real system
if [ -z "${IPKG_INSTROOT}" ]; then
	ZAPRET_DIR=/opt/zapret2
	ZAPRET_BASE=/opt/zapret2
	ZAPRET_INITD=/etc/init.d/zapret2
	ZAPRET_CFG=/etc/config/zapret2
	ZAPRET_CONFIG=/opt/zapret2/config
	ZAPRET_CONFIG_DEF="/opt/zapret2/config.default"
	OPENWRT_FW_INCLUDE=/etc/firewall.zapret2
	# check main config
	sh -n "${ZAPRET_CONFIG}" 2>/dev/null || cp -f "${ZAPRET_CONFIG_DEF}" "${ZAPRET_CONFIG}"
	if ! sh -n "${ZAPRET_CONFIG}" 2>/dev/null ; then
		ps w | grep '/opt/zapret2/nfq2/nfqws2' | grep -v grep | awk '{print $1}' | xargs -r kill -9
		exit 0
	fi
	. "${ZAPRET_CONFIG}"
	. "${ZAPRET_BASE}/common/base.sh"
	. "${ZAPRET_BASE}/common/fwtype.sh"
	. "${ZAPRET_BASE}/common/nft.sh"
	. "${ZAPRET_BASE}/common/installer.sh"
	${ZAPRET_INITD} running && ${ZAPRET_INITD} stop >/dev/null 2>&1
	${ZAPRET_INITD} disable >/dev/null 2>&1
	ps w | grep '/opt/zapret2/nfq2/nfqws2' | grep -v grep | awk '{print $1}' | xargs -r kill -9
	remove_openwrt_firewall
	nft_del_table
	restart_openwrt_firewall
fi
exit 0
