#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1

BIN="/usr/bin/tg-mtproxy-client"

start_service() {
    [ -x "$BIN" ] || return 1
    procd_open_instance
    procd_set_param command "$BIN" -listen "0.0.0.0:1443" -tunnel-url "wss://213.176.74.63.nip.io/ws" -tunnel-secret "63d91c9c6fbc14b59043696af837774c1f90ecabe112b97113e5d0b289900070"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
